### ISSUE TITLE
Roadmap y canva

### ISSUE THREAD

**Issue by Luz1727** [SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-reciclaenexus#16]
[roadmap-Canva.pdf](https://github.com/user-attachments/files/17547148/roadmap-Canva.pdf)

link:

https://github.com/SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-reciclaenexus/issues?q=is%3Aissue+is%3Aclosed

**Comment by ToniDepp** [comment]
**Portada:** Cuenta con todos los elementos 25/25
**Procedimiento:** Describe bien los procesos 25/25
**Figuras, ilustraciones y fotografías:** 25/ 25
**Resultados y conclusión:** Bien 25/25
**Puntos:** 100/100
**Calificación final:** 20%

**Comment by josealfredo79** [comment]
bien hecho y revisado
