### ISSUE TITLE
CONTADOR Y WALLET

### ISSUE THREAD

**Issue by saul19bautista** [SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-reciclaenexus#17]
[contadorywallet.pdf](https://github.com/user-attachments/files/18093655/contadorywallet.pdf)

**Comment by AmilkarVladimiR** [comment]
Portada y escudos institucionales: 25 puntos
Descripción detallada del procedimiento: 25 puntos
Incluye ilustraciones: 25 puntos
Resultado y conclusión: 25 puntos
Porcentaje obtenido 100% = 50 puntos

**Comment by josealfredo79** [comment]
bien hecho y revisado..
